---
- name: stop display-manager service
  ansible.builtin.service:
    name: display-manager
    state: stopped
  failed_when: false
  become: true

- name: copy bash files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ package_dir }}/{{ item | basename }}"
    force: true
  with_fileglob:
    - files/*.bash
  become: true

- name: install dependencies
  ansible.builtin.apt:
    name:
      - fonts-dejavu              # font family with good unicode support; lowers the chance of seeing boxes instead of characters
      - fonts-dejavu-extra        # font family with good unicode support; lowers the chance of seeing boxes instead of characters even more
      - fonts-noto                # coverage bazooka; covers a lot of unicode characters
      - ttf-mscorefonts-installer # font like Times and Verdana
      - lightdm                   # display manager
      - accountsservice           # lightdm dependency
      - x11-xserver-utils         # xset and xsetroot
      - xdotool                   # for mouse manipulation
      - unclutter                 # hides the mouse cursor
      - matchbox-window-manager   # window manager
      - upower                    # if missing, causes error messages like the following when running Chromium:
      # Failed to call method: org.freedesktop.DBus.Properties.Get: ↵
      # object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: ↵
      # The name org.freedesktop.UPower was not provided by any .service files
      - chromium-browser          # displays the web application
    state: present
  become: true

- name: compute busyscreen_kiosk defaults
  set_fact:
    busyscreen_kiosk: >
      {{
      busyscreen_kiosk | default({})
      | combine({'user': ansible_facts.user_id})
      }}
  when: busyscreen_kiosk is undefined

- name: copy busy-screen-kiosk
  ansible.builtin.copy:
    src: files/busy-screen-kiosk
    dest: "{{ package_dir }}/bin/busy-screen-kiosk"
    mode: "0755"
    force: true
  become: true

- name: copy busy-screen-kiosk.desktop
  ansible.builtin.template:
    src: templates/busy-screen-kiosk.desktop.j2
    dest: "/usr/share/xsessions/{{ lightdm_user_session }}.desktop"
    mode: "0644"
    force: true
  become: true

- name: configure lightdm to use busyscreen session
  community.general.ini_file:
    path: /etc/lightdm/lightdm.conf
    no_extra_spaces: true
    section: "Seat:*"
    option: "user-session"
    value: "{{ lightdm_user_session }}"
  become: true

- name: configure lightdm to use auto-login {{ busyscreen_kiosk.user }}
  community.general.ini_file:
    path: /etc/lightdm/lightdm.conf
    no_extra_spaces: true
    section: "Seat:*"
    option: "autologin-user"
    value: "{{ busyscreen_kiosk.user }}"
  become: true

- name: enable display-manager service
  ansible.builtin.systemd:
    name: display-manager.service
    daemon_reload: true
    enabled: true
  become: true

- name: set default target to graphical
  ansible.builtin.shell: systemctl set-default graphical.target
  become: true

- name: restart display-manager service
  ansible.builtin.systemd:
    name: display-manager.service
    state: restarted
  become: true
