---
- name: install busyscreen
  block:
    - name: create package directory
      ansible.builtin.file:
        path: "{{ package_dir }}"
        state: directory
      become: true

    - name: copy files
      ansible.posix.synchronize:
        src: files/
        dest: "{{ package_dir }}/"
      become: true

    - name: make busyscreen executable
      file:
        dest: "{{ package_dir }}/bin/busy-screen"
        mode: "0755"
      become: true

    - name: symlink busyscreen
      ansible.builtin.file:
        src: "{{ package_dir }}/bin/busy-screen"
        dest: /usr/local/bin/busy-screen
        state: link
      become: true

    - name: remove outdated artifacts
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/profile.d/busy-screen_path.sh
      become: true

    - name: explain busyscreen
      vars:
        marker_begin_latin1: "MARKER_BEGIN"
        marker_begin_unicode: "┴┬┴┤´Ｏ´)ﾉ"
        marker_end_latin1: "MARKER_END"
        marker_end_unicode: "​​​"
        path: /etc/motd
      block:
        - name: convert markers to latin1
          ansible.builtin.replace:
            path: "{{ path }}"
            regexp: "{{ item.regexp }}"
            replace: "{{ item.replace }}"
          loop:
            - { regexp: "{{ marker_begin_unicode | regex_escape() }}", replace: "{{ marker_begin_latin1 }}" }
            - { regexp: "{{ marker_end_unicode | regex_escape() }}", replace: "{{ marker_end_latin1 }}" }
        - name: update block
          ansible.builtin.blockinfile:
            path: /etc/motd
            create: true
            mode: "0644"
            marker: "{mark}"
            marker_begin: "{{ marker_begin_latin1 }} Busy Screen" # Σ(‘Д’⁕)
            block: |2
                  GUI: A kiosk-mode web application should be running on the attached screen.
                  HELP: busy-screen
            marker_end: "{{ marker_end_latin1 }}"
        - name: convert markers to unicode
          ansible.builtin.replace:
            path: "{{ path }}"
            regexp: "{{ item.regexp }}"
            replace: "{{ item.replace }}"
          loop:
            - { regexp: "{{ marker_begin_latin1 }}", replace: "{{ marker_begin_unicode }}" }
            - { regexp: "{{ marker_end_latin1 }}", replace: "{{ marker_end_unicode }}" }
      become: true
