---
- name: copy bash files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ package_dir }}/{{ item | basename }}"
    force: true
  with_fileglob:
    - files/*.bash
  become: true

- name: install dependencies
  ansible.builtin.apt:
    name: [ lighttpd ]
    state: present
  become: true

- name: change server.document-root in /etc/lighttpd/lighttpd.conf to {{ package_dir }}/busy-screen-web-display
  ansible.builtin.lineinfile:
    path: /etc/lighttpd/lighttpd.conf
    regexp: '^server\.document-root\s*='
    line: 'server.document-root        = "{{ package_dir }}/busy-screen-web-display"'
  notify: "restart lighttpd"
  become: true

- name: build query params
  set_fact:
    busyscreen_web_display_query_params: >
      {{
      (busyscreen_web_display_query_params | default([])) + [(item.key|string|urlencode) + '=' + (item.value|string|urlencode)]
      }}
  with_dict: "{{ busyscreen_web_display_args }}"

- name: set BUSYSCREEN_KIOSK_URL
  ansible.builtin.lineinfile:
    path: /etc/environment
    state: present
    create: yes
    mode: "0644"
    regexp: '^BUSYSCREEN_KIOSK_URL='
    line: "BUSYSCREEN_KIOSK_URL='http://localhost/?{{ busyscreen_web_display_query_params | join('&') }}'"
  become: true
  notify: reboot

- name: enable lighttpd service
  ansible.builtin.systemd:
    name: lighttpd.service
    daemon_reload: true
    enabled: true
  become: true

- name: build artifact if necessary
  local_action:
    module: ansible.builtin.shell
    chdir: "{{ project_dir }}"
    cmd: "./gradlew --no-daemon clean jsBrowserProductionWebpack"
    creates: "{{ busyscreen_web_display_build_artifact }}"
  run_once: true

- name: copy artifact
  ansible.posix.synchronize:
    src: "{{ busyscreen_web_display_build_artifact }}/"
    dest: "{{ package_dir }}/busy-screen-web-display/"
  become: true

- name: restart lighttpd service
  ansible.builtin.systemd:
    name: lighttpd.service
    state: restarted
  become: true
  notify: "restart display-manager"

- name: restart display-manager service
  ansible.builtin.systemd:
    name: display-manager.service
    state: restarted
  become: true
