---
# needed on outdated systems, for dependencies to be installable
- name: configure apt to allow release info change
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/99allow-release-info-change
    state: present
    create: yes
    line: Acquire::AllowReleaseInfoChange::Suite "true";
  become: true

- name: update apt packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
